repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      args: ["--line-length=150"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.21'
    hooks:
    - id: isort
      args: ["--multi-line=3", "--trailing-comma", "--force-grid-wrap=0","--use-parentheses", "--line-width=150"]

