version: '3.7'

services:

  localstack:
    image: localstack/localstack:0.11.4
    container_name: "awscostreporter-localstack-0.11.4"
    ports:
      - "4566-4593:4566-4593"
    environment:
      - SERVICES=s3,sqs

  wait:
    image: waisbrot/wait
    depends_on:
      - localstack
    environment:
      - TARGETS=localstack:4566