version: 2

jobs:
  test:
    working_directory: ~/app/
    docker:
      - image: cimg/python:3.12
      - image: localstack/localstack:4.3.0

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          key: deps-v3-{{ .Branch }}-{{ checksum "uv.lock" }}
      - run:
          name: Upgrade uv
          command: |
            pip install uv -U
      - run:
          name: install dependencies
          command: |
            uv sync
      - run:
          name: prepare boto3 credentials and awscli (Set via ENVARS[AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY])
          command: |
            # create ~/.aws/config
            echo "Creating: ~/.aws/config"
            mkdir -p ~/.aws
            cat <<EOT > ~/.aws/config
            [default]
            region = ${AWS_DEFAULT_REGION}
            output = json

            [profile ${AWS_PROFILE}]
            region = ${AWS_DEFAULT_REGION}
            source_profile = default
            EOT

            # create .aws/credentials
            echo "Creating: ~/.aws/credentials"
            cat <<EOT > ~/.aws/credentials
            [default]
            aws_access_key_id = ${CIRCLECI_AWS_ACCESS_KEY_ID}
            aws_secret_access_key = ${CIRCLECI_AWS_SECRET_ACCESS_KEY}
            EOT

            # for deployment
            pip install awscli

      - save_cache:
          key: deps-v3-{{ .Branch }}-{{ checksum "uv.lock" }}
          paths:
            - "/home/circleci/.aws"
            - "/home/circlci/.local"
            - "/usr/local/bin"
      - run:
          name: run tests
          command: |
            mkdir test-reports
            pipenv run pytest -v --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - run:
          name: code checks (flake8)
          command: |
            make check


workflows:
  version: 2
  test:
    jobs:
      - test

