AWSTemplateFormatVersion : 2010-09-09
Description: Add Scheduled Lambda Trigger


Parameters:

  StageName:
    Type: String
    AllowedValues:
    - prd
    - dev
    - stg

  FunctionArn:
    Type: String


Resources:

  CostManagerTriggerRule:
    Type: AWS::Events::Rule
    Properties:
      Description: 'CostManagerTriggerRule'
      Name: !Sub 'aws-cost-report-${StageName}-pacioli.handlers.events.post_status'
      ScheduleExpression: "cron(0 0 ? * MON,WED,FRI *)"
      State: "ENABLED"
      Targets:
        -
          Arn: !Ref FunctionArn
          # ID must take the form: (Max 64 characters)
          # {Lambda Function Name}-{STAGE}-{internal funcname}
          Id: !Sub 'aws-cost-report-${StageName}-pacioli.handlers.events.post_status'
